# Generated by Django 3.1.3 on 2020-12-22 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201222_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='block_category',
            new_name='blog_category',
        ),
        migrations.RenameField(
            model_name='blogcategory',
            old_name='blog_category',
            new_name='category_name',
        ),
    ]
