# Generated by Django 3.1.3 on 2021-01-22 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('read_statistics', '0003_readdetail_read_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readdetail',
            name='read_detail',
        ),
        migrations.AlterField(
            model_name='readdetail',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
