"""
Django settings for SecurityWeb project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
import sys


BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0,os.path.join(BASE_DIR,'apps'))

# Quick-start development se ttings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!=!o&#qeukww+nl2i=yqm*&l*m!sln%%(j95h!q^99(_0fk3(w'


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Database

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'security_web_db',
        'USER': 'root',
        'PASSWORD': 'labi0110',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


#发送邮箱设置
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.googlemail.com'
EMAIL_PORT=587
EMAIL_HOST_USER='jiayue0110@gmail.com'
EMAIL_HOST_PASSWORD=' ' #授权码
EMAIL_SUBJECT_PREFIX='[SecurityWeb]'
EMAIL_USE_TLS=True #是否启动TLS链接




