# Generated by Django 3.1.3 on 2021-01-10 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210110_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readnum',
            old_name='readnum_with_blog',
            new_name='blog',
        ),
    ]
