# Generated by Django 3.1.3 on 2021-01-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0002_readdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='readdetail',
            name='read_detail',
            field=models.SlugField(default='abc'),
        ),
    ]
